### ISSUE TITLE
Ask Jake to stand in the corner of the room and move every 2 minutes.

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#24]
cc @bocajnotnef

**Comment by SensibleSalmon** [comment]
This sounds suspiciously like an inside joke I missed from today's meeting

**Comment by ctb** [comment]
On Tue, Jun 23, 2015 at 02:27:27PM -0700, Jake Fenton wrote:

> This sounds suspiciously like an inside joke I missed from today's meeting

(We have a light switch that needs regular motion or otherwise the
light goes out.)

**Comment by drtamermansour** [comment]
---------- Forwarded message ----------
From: Tamer Mansour <drtamermansour@gmail.com>
Date: Sun, Jun 21, 2015 at 2:59 PM
Subject: Re: [HPCC #15041] Jobs start and crash
To: "general@rt.hpcc.msu.edu" <general@rt.hpcc.msu.edu>


Hi,
I am afraid I never heard back from you. This problem is really hindering
my work. I hope we can find a way to solve that.

Thanks

**Comment by SensibleSalmon** [comment]
Alternatively: an oscillating fan. Or a lab cat. Or an oscillating fan, yarn _and_ a lab cat.
