### ISSUE TITLE
Challenges/etc to surface at the Moore Foundation site visit

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#43]
"What problems have you encountered (scientific, recruiting, recognition etc.)? What new methods or advances are you exploring? What interesting work are you watching?"

Please place suggestions below.

**Comment by mr-c** [comment]
Problems: funding for khmer, et cetera

**Comment by tracykteal** [comment]
- New tools are generated, like in the DIB lab, but since there are so many new tools being developed, it's often difficult to have them adopted. Users must find the tool (discoverability), evaluate if it fits their needs and if it's better/worse/different than existing tools, learn how to use it generally and then how to apply it to their specific work. If you ask people why they use the software they do, the general response is because it was in a paper they read where the authors do similar work or their lab mate or collaborator uses it and/or they managed to get through the installation process or follow the documentation. There is not often a lot of scientific justification for software or tool use choice. 
- Scaling training efforts on these tools, or training in general, is a challenge. It's possible to help in small groups or one on one but it doesn't scale well.

**Comment by drtamermansour** [comment]
Should we tune the problems/discussions to the context of Moore grant?? or we are taking about the broad science ??

**Comment by ctb** [comment]
On Tue, Sep 01, 2015 at 05:09:12PM -0700, Tamer Mansour wrote:

> Should we tune the problems/discussions to the context of Moore grant?? 

Mmmh... not sure.  Let's surface the problems first, then we can tailor.

**Comment by drtamermansour** [comment]
- +1 for the problem of bioinformatic tools maze: Usually the papers announcing new tools are too much technical and over the head of most biologists. The papers the compare different tools and suggest given tools for specific applications are few and usually lack appropriate controls because they usually lack funding for doing enough experiments to define the truth. Also they are outdated very fast by new versions and new tools. Developing pipelines that have good controls and could be run easily with new tools and versions are very helpful to update benchmarks.
- The integrative analysis of the hugely growing high throughput data. We have big investment in the databases of high throughput data like NGS. However we are far from making use of these hugely accumulating data. Our lab has developed diginorm which helps minimizing the hardware burden required to do this analysis. Still there are several problems in data sharing, cloud computing, statistical models and plateform specific controls.

**Comment by ctb** [comment]
Thanks all, keep 'em coming!
